spring.application.port=8081
spring.application.name=savemore
spring.datasource.url=jdbc:mysql://localhost:3306/savemore
spring.datasource.username=root
spring.datasource.password=638033

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=aVerySecureRandomAndLongSecretKeyForYourSpringBootApplicationThatIsAtLeast512BitsLong
jwt.expiration=86400000